const products = [
    {
      id: 1,
      name: "Apple iPhone 13 (128GB) - Starlight Light Blue",
      category: "Smart Phone",
      availability: 49,
      price: 122.0,
      image: "https://opc.webdigify.com/OPC03/OPC090_quickstore/image/cache/catalog/07-1000x1000.jpg",
      type: "iPhone",
      processor: "A15 Bionic",
      memory: "128GB",
      os: "iOS",
    },
    {
      id: 11,
      name: "Samsung Galaxy S21",
      category: "Smart Phone",
      availability: 30,
      price: 999.0,
      image: "https://opc.webdigify.com/OPC03/OPC090_quickstore/image/cache/catalog/07-1000x1000.jpg",
      type: "Android",
      processor: "Exynos 2100",
      memory: "256GB",
      os: "Android",
    },
    {
      id: 111,
      name: "Google Pixel 6",
      category: "Smart Phone",
      availability: 15,
      price: 799.0,
      image: "https://opc.webdigify.com/OPC03/OPC090_quickstore/image/cache/catalog/07-1000x1000.jpg",
      type: "Android",
      processor: "Google Tensor",
      memory: "128GB",
      os: "Android",
    },
    {
      id: 1111,
      name: "OnePlus 9 Pro",
      category: "Smart Phone",
      availability: 25,
      price: 899.0,
      image: "https://opc.webdigify.com/OPC03/OPC090_quickstore/image/cache/catalog/07-1000x1000.jpg",
      type: "Android",
      processor: "Snapdragon 888",
      memory: "256GB",
      os: "Android",
    },
    {
      id: 12,
      name: "Apple iPhone 12 Mini",
      category: "Smart Phone",
      availability: 10,
      price: 699.0,
      image: "https://opc.webdigify.com/OPC03/OPC090_quickstore/image/cache/catalog/07-1000x1000.jpg",
      type: "iPhone",
      processor: "A14 Bionic",
      memory: "64GB",
      os: "iOS",
    },
    {
      id: 122,
      name: "Xiaomi Redmi Note 10",
      category: "Smart Phone",
      availability: 20,
      price: 249.0,
      image: "https://opc.webdigify.com/OPC03/OPC090_quickstore/image/cache/catalog/07-1000x1000.jpg",
      type: "Android",
      processor: "Snapdragon 678",
      memory: "128GB",
      os: "Android",
    },
    {
      id: 13,
      name: "Sony Xperia 1 III",
      category: "Smart Phone",
      availability: 5,
      price: 1299.0,
      image: "https://opc.webdigify.com/OPC03/OPC090_quickstore/image/cache/catalog/07-1000x1000.jpg",
      type: "Android",
      processor: "Snapdragon 888",
      memory: "256GB",
      os: "Android",
    },
    // Add more products as needed
  ];
  
  export default products;
  